### ISSUE TITLE
Improvement of search box

### ISSUE THREAD

**Issue by mlhsn** [arifszn/awesome-shortcuts#39]
![image](https://user-images.githubusercontent.com/42032351/180382254-989859b3-37ef-46d8-ba8a-347d08cb7ae1.png)

- Dim the text color to bit light color
- On click remove the placeholder text

**Comment by Tathagat27** [comment]
I would like to work on this.

**Comment by arifszn** [comment]
Sure. Assigning it to you then.

**Comment by arifszn** [comment]
Resolved via #76.
